const FIXED_PERMISSIONS = {
  MENU_MANAGEMENT: 'menu_management',
  ORDER_MANAGEMENT: 'order_management', 
  BILLING_MANAGEMENT: 'billing_management',
  SPACE_MANAGEMENT: 'space_management',
  TASK_MANAGEMENT: 'task_management',
  EXPENSE_MANAGEMENT: 'expense_management',
  REPORTS_ANALYTICS: 'reports_analytics',
  EMPLOYEE_MANAGEMENT: 'employee_management',
  CUSTOMER_MANAGEMENT: 'customer_management',
  HOTEL_IMAGES: 'hotel_images',
  LANDING_PAGE_MANAGEMENT: 'landing_page_management',
  ABOUT_US_MANAGEMENT: 'about_us_management',
  CUISINE_GALLERY_MANAGEMENT: 'cuisine_gallery_management',
  WELCOME_SECTION_MANAGEMENT: 'welcome_section_management',
  CONTACT_US_MANAGEMENT: 'contact_us_management'
};

const PERMISSION_LABELS = {
  [FIXED_PERMISSIONS.MENU_MANAGEMENT]: 'Menu Management',
  [FIXED_PERMISSIONS.ORDER_MANAGEMENT]: 'Order Management',
  [FIXED_PERMISSIONS.BILLING_MANAGEMENT]: 'Billing Management',
  [FIXED_PERMISSIONS.SPACE_MANAGEMENT]: 'Space Management',
  [FIXED_PERMISSIONS.TASK_MANAGEMENT]: 'Task Management',
  [FIXED_PERMISSIONS.EXPENSE_MANAGEMENT]: 'Expense Management',
  [FIXED_PERMISSIONS.REPORTS_ANALYTICS]: 'Reports & Analytics',
  [FIXED_PERMISSIONS.EMPLOYEE_MANAGEMENT]: 'Employee Management',
  [FIXED_PERMISSIONS.CUSTOMER_MANAGEMENT]: 'Customer Management',
  [FIXED_PERMISSIONS.HOTEL_IMAGES]: 'Hotel Images',
  [FIXED_PERMISSIONS.LANDING_PAGE_MANAGEMENT]: 'Landing Page Management',
  [FIXED_PERMISSIONS.ABOUT_US_MANAGEMENT]: 'About Us Management',
  [FIXED_PERMISSIONS.CUISINE_GALLERY_MANAGEMENT]: 'Cuisine Gallery Management',
  [FIXED_PERMISSIONS.WELCOME_SECTION_MANAGEMENT]: 'Welcome Section Management',
  [FIXED_PERMISSIONS.CONTACT_US_MANAGEMENT]: 'Contact Us Management'
};

const PERMISSION_ICONS = {
  [FIXED_PERMISSIONS.MENU_MANAGEMENT]: '📋',
  [FIXED_PERMISSIONS.ORDER_MANAGEMENT]: '📝',
  [FIXED_PERMISSIONS.BILLING_MANAGEMENT]: '💰',
  [FIXED_PERMISSIONS.SPACE_MANAGEMENT]: '🪑',
  [FIXED_PERMISSIONS.TASK_MANAGEMENT]: '✅',
  [FIXED_PERMISSIONS.EXPENSE_MANAGEMENT]: '💸',
  [FIXED_PERMISSIONS.REPORTS_ANALYTICS]: '📊',
  [FIXED_PERMISSIONS.EMPLOYEE_MANAGEMENT]: '👥',
  [FIXED_PERMISSIONS.CUSTOMER_MANAGEMENT]: '🧑‍🤝‍🧑',
  [FIXED_PERMISSIONS.HOTEL_IMAGES]: '🖼️',
  [FIXED_PERMISSIONS.LANDING_PAGE_MANAGEMENT]: '🌐',
  [FIXED_PERMISSIONS.ABOUT_US_MANAGEMENT]: 'ℹ️',
  [FIXED_PERMISSIONS.CUISINE_GALLERY_MANAGEMENT]: '🍽️',
  [FIXED_PERMISSIONS.WELCOME_SECTION_MANAGEMENT]: '🏨',
  [FIXED_PERMISSIONS.CONTACT_US_MANAGEMENT]: '📞'
};

module.exports = {
  FIXED_PERMISSIONS,
  PERMISSION_LABELS,
  PERMISSION_ICONS
};