// src/config/fixedPermissions.js
export const FIXED_PERMISSIONS = {
  // Main permissions that will be displayed in sidebar
  MENU_MANAGEMENT: 'menu_management',
  ORDER_MANAGEMENT: 'order_management', 
  BILLING_MANAGEMENT: 'billing_management',
  SPACE_MANAGEMENT: 'space_management',
  TASK_MANAGEMENT: 'task_management',
  EXPENSE_MANAGEMENT: 'expense_management',
  REPORTS_ANALYTICS: 'reports_analytics',
  EMPLOYEE_MANAGEMENT: 'employee_management',
  CUSTOMER_MANAGEMENT: 'customer_management'
};

export const PERMISSION_LABELS = {
  [FIXED_PERMISSIONS.MENU_MANAGEMENT]: 'Menu Management',
  [FIXED_PERMISSIONS.ORDER_MANAGEMENT]: 'Order Management',
  [FIXED_PERMISSIONS.BILLING_MANAGEMENT]: 'Billing Management',
  [FIXED_PERMISSIONS.SPACE_MANAGEMENT]: 'Space Management',
  [FIXED_PERMISSIONS.TASK_MANAGEMENT]: 'Task Management',
  [FIXED_PERMISSIONS.EXPENSE_MANAGEMENT]: 'Expense Management',
  [FIXED_PERMISSIONS.REPORTS_ANALYTICS]: 'Reports & Analytics',
  [FIXED_PERMISSIONS.EMPLOYEE_MANAGEMENT]: 'Employee Management',
  [FIXED_PERMISSIONS.CUSTOMER_MANAGEMENT]: 'Customer Management'
};

export const PERMISSION_ICONS = {
  [FIXED_PERMISSIONS.MENU_MANAGEMENT]: '📋',
  [FIXED_PERMISSIONS.ORDER_MANAGEMENT]: '📝',
  [FIXED_PERMISSIONS.BILLING_MANAGEMENT]: '💰',
  [FIXED_PERMISSIONS.SPACE_MANAGEMENT]: '🪑',
  [FIXED_PERMISSIONS.TASK_MANAGEMENT]: '✅',
  [FIXED_PERMISSIONS.EXPENSE_MANAGEMENT]: '💸',
  [FIXED_PERMISSIONS.REPORTS_ANALYTICS]: '📊',
  [FIXED_PERMISSIONS.EMPLOYEE_MANAGEMENT]: '👥',
  [FIXED_PERMISSIONS.CUSTOMER_MANAGEMENT]: '🧑‍🤝‍🧑'
};

export const PERMISSION_PATHS = {
  [FIXED_PERMISSIONS.MENU_MANAGEMENT]: '/menu',
  [FIXED_PERMISSIONS.ORDER_MANAGEMENT]: '/orders',
  [FIXED_PERMISSIONS.BILLING_MANAGEMENT]: '/billing',
  [FIXED_PERMISSIONS.SPACE_MANAGEMENT]: '/spaces',
  [FIXED_PERMISSIONS.TASK_MANAGEMENT]: '/tasks',
  [FIXED_PERMISSIONS.EXPENSE_MANAGEMENT]: '/expenses',
  [FIXED_PERMISSIONS.REPORTS_ANALYTICS]: '/reports',
  [FIXED_PERMISSIONS.EMPLOYEE_MANAGEMENT]: '/employees',
  [FIXED_PERMISSIONS.CUSTOMER_MANAGEMENT]: '/customers'
};

